### ISSUE TITLE
Problem show component video

### ISSUE THREAD

**Issue by danilobbezerra** [msfragala/sanity-plugin-youtube-input#1]
Hi, I'm using your plugin because I want to display videos in posts on my blog.
I created the blog using tamplate: https://vercel.com/templates/next.js/blog-next-sanity

I did the procedures to install and configure the key, I can already see the fields on YouTube in Sanity.

But when rendering it is not showing, could you help me, I think I need to do something in this project so that it recognizes the field?

in the browser console it is giving the following message:
Unknown block type "youtubeEmbed", specify a component for it in the `components.types` prop

**Comment by msfragala** [comment]
Sanity plugins can't control how data renders on the frontend — they only exist within the Sanity studio. So this plugin only handles pulling YouTube data into your studio. You'll have to render the YouTube embed yourself, or use another library.

From the message error you're seeing in the console, I'm guessing you're trying to use this inside block content. You can add a custom PortableText component with [react-portabletext](https://github.com/portabletext/react-portabletext) to do this. I recommend following the documentation there to set that up
